[package]
name = "stonks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.1"
chrono = "0.4.38"
polars = { version = "0.42.0", features = ["lazy", "csv"] }
